let nombre = "Harvey";
let apellido = "Muralla";
let edad = 34;
let genero = "Masculino";
let email = "myemail@gmail.com";
let camisa = "Llevo camisa roja";
let pantalones = "jean";
let pies_lleva_calzado = false;
let color_del_pelo = "Negro";
let tipo_de_pelo = "liso";
let color_de_ojos = "negros";
let color_de_piel = "blanco";
let altura = 1.85;
let peso = 80;

console.log("Mi nombre es: " + nombre);
console.log("Mi apellido es: " + apellido);
console.log("Mi edad es: " + edad);
console.log("Mi género es: " + genero);
console.log("Mi correo es: " + email);
console.log("Mi camisa es: " + camisa);
console.log("El pantalón que tengo: " + pantalones);
console.log("Tengo Calzado: " + pies_lleva_calzado);
console.log("Mi color de Pelo: " + color_del_pelo);
console.log("Que tipo de pelo tengo: " + tipo_de_pelo);
console.log("El color de mis ojos: " + color_de_ojos);
console.log("El color de mi piel: " + color_de_piel);
console.log("Mi altura es : " + altura + " metros");
console.log("Peso es: " + peso + " kg");